/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2014-11-19 10:10:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.__0040admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/_include/lib_admin.jsp", Long.valueOf(1412660826895L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    java.lang.Throwable exception = org.apache.jasper.runtime.JspRuntimeLibrary.getThrowable(request);
    if (exception != null) {
      response.setStatus(javax.servlet.http.HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body { background:#E0E0E0;}\r\n");
      out.write("td   { font-size:12px; color:#ffffff; }\r\n");
      out.write("a    { color:#ffffff; text-decoration:none; }\r\n");
      out.write("a:hover { text-decoration:underline; }\r\n");
      out.write("b\t{color:#A0A0A0}\r\n");
      out.write(".arrow{\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("\twidth:33px;\r\n");
      out.write("\theight:38px;\r\n");
      out.write("\tz-index:111;\r\n");
      out.write("\tleft:500px;\r\n");
      out.write("\ttop:50px;\r\n");
      out.write("\tcursor:pointer;\r\n");
      out.write("\t-webkit-transition: -webkit-transform 0.4s ease !important;\r\n");
      out.write("\t-moz-transition: -webkit-transform 0.4s ease !important;\r\n");
      out.write("\t-ms-transition: -webkit-transform 0.4s ease !important;\r\n");
      out.write("\ttransition: transform 0.4s ease !important;\t\r\n");
      out.write("}\r\n");
      out.write(".opacity{\r\n");
      out.write("\topacity:.5;\r\n");
      out.write("}\r\n");
      out.write(".rotate{\t\r\n");
      out.write("\ttransform:rotate(180deg);\t\r\n");
      out.write("}\r\n");
      out.write(".close{\r\n");
      out.write("\t-webkit-transform:translateY(-60px);\r\n");
      out.write("\t-moz-transform:translateY(-60px);\r\n");
      out.write("\t-ms-transform:translateY(-60px);\r\n");
      out.write("\ttransform:translateY(-60px);\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write('\r');
      out.write('\n');

if ( session.getAttribute ("sesAdminID") == null || session.getAttribute ("sesAdminID").equals ( "" ) ) {
	out.println ("<script language='javascript'>alert('您需重新登入.');location.href='/@admin';</script>");
	return;
}

      out.write('\r');
      out.write('\n');
	
	String admin_ip  =request.getRemoteAddr();
	String sesAdminName = (String)session.getAttribute ("sesAdminName");
	String MainAdmin = (String)session.getAttribute ("sesMainAdmin");
	String adminID = (String)session.getAttribute ("sesAdminID");
	String adminName = (String)session.getAttribute ("sesAdminName"); 
	int sum = 0;

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"script.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery-1.11.1.min.js\"></script>\t\r\n");
      out.write("<body >\r\n");
      out.write("<nav>\r\n");
      out.write("\t<div style=\"top:0px;left:0px;height:70px;background-color:#000000;\">\r\n");
      out.write("\t\t<div style=\"float:left\"><img src=\"/images/logo.png\"></div>\r\n");
      out.write("\t\t\t<div ><font size=\"5\" color=\"white\" >目前使用者:");
      out.print(sesAdminName);
      out.write("  IP:");
      out.print(admin_ip);
      out.write("</font></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t<ul class=\"menu\" id=\"menu\">\r\n");
      out.write("\t<li><a href=\"logout.jsp\" class=\"menulink\">登出管理者</a></li>\r\n");
      out.write("\t");
if(MainAdmin.equals("1")){
      out.write("\r\n");
      out.write("\t<li><a href=\"#\" class=\"menulink\">後台使用者資訊及管理</a>\r\n");
      out.write("\t\t<ul>\t\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"sub\">使用者</a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"topline\"><a href='adminuser.jsp' target='incFrame'>管理使用者</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='adminfilter.jsp' target='incFrame' >限制IP登入後台</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li><a href='contact_form.jsp' target='incFrame' >客戶訊息查詢</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t");
}
      out.write("\r\n");
      out.write("\t<li>\r\n");
      out.write("\t\t<a href='newslist.jsp' target='incFrame'  class=\"menulink\">最新消息管理</a>\r\n");
      out.write("\t</li>\r\n");
      out.write("</ul>\r\n");
      out.write("<div class=\"arrow\"><img src=\"/images/arrow.png\" width=\"33\" height=\"38\" border=\"0\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</nav>\r\n");
      out.write("<div id=\"container\" >\r\n");
      out.write("\t<iframe name=\"incFrame\" id=\"incFrame\" frameborder=0 width=\"100%\" height=\"100%\" src=\"/images/logo_big.png\"></iframe>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script language='javascript'>\r\n");
      out.write("\tvar menu=new menu.dd(\"menu\");\r\n");
      out.write("\tmenu.init(\"menu\",\"menuhover\");\r\n");
      out.write("\t(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('.arrow').click(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('nav').toggleClass('close');\t\r\n");
      out.write("\t\t\t$('#container').toggleClass('close');\r\n");
      out.write("\t\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t\t$('.arrow').toggleClass('rotate');\r\n");
      out.write("\t\t\t\t$('nav').toggleClass('opacity');\r\n");
      out.write("\t\t\t},500);\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t})();\r\n");
      out.write("</script>\r\n");
      out.write("<noscript>Your browser does not support Script!</noscript>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
