/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2014-11-19 11:32:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.__0040admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;
import teachDB.DbBean;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

if ( session.getAttribute ("sesAdminID") != null) {
		response.sendRedirect ("admin.jsp");
		return;
}

String adminID = "";
String adminPW = "";

String act = request.getParameter("act");
String admin_ip  =request.getRemoteAddr();
String rand = (String)session.getAttribute("rand");
	String input = request.getParameter("rand");

if ( act != null ) {
	if ( act.equals("process") ) {
		try {
			adminID = request.getParameter("adminID").trim();
			adminPW = request.getParameter("adminPW").trim();
			boolean checkip = false;
			DbBean db = new DbBean();
				List iplist = db.SelectRS("select ipaddress from adminfilter where deleteflag = 0 ");				
				if( iplist != null && iplist.size() > 0 ) {
					for ( int i = 0; i < iplist.size(); i++ ) {
						Map ipmap = (Map)iplist.get(i); 
						if( ipmap.get("ipaddress").toString().equals(admin_ip) ) {
							checkip = true;
						}else{
							out.println("<script>alert('未授權');top.location.href='/';</script>");
						}			
					} 
				}else{
					checkip = true;
				}
				if(checkip){
					List loginList = new ArrayList();
					loginList.add(adminID);
					loginList.add(adminPW);
					List userlist = db.SelectRSwhere("select * from adminuser where a_userid=? and a_passwd = ?",loginList);
					
					if ( userlist != null && userlist.size()>0 && rand.equals(input)) { 
						for ( int i = 0; i < userlist.size(); i++ ) {
							Map usermap = (Map)userlist.get(i); 
								session.setAttribute ("sesMainAdmin",usermap.get("admin").toString());
								session.setAttribute ("sesAdminName",usermap.get("a_username").toString());
						}
						session.setAttribute ("sesAdminID",adminID);
						response.sendRedirect ("admin.jsp");
						return;
					} else {
						if(!rand.equals(input)){
							out.println ("<script language='javascript'>alert('驗證碼輸入錯誤.');location.href='/@admin';</script><noscript>Your browser does not support Script!</noscript>");
						}else{
							out.println ("<script language='javascript'>alert('帳號或密碼錯誤.');location.href='/@admin';</script><noscript>Your browser does not support Script!</noscript>");
						}
						return;
					}
				}
			
		} catch ( Exception e ) {
			out.println ("<script language='javascript'>alert('非法存取.');location.href='/@admin';</script><noscript>Your browser does not support Script!</noscript>");
			return;
		}
	}
}

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>眾騰會計師事務所</title>\r\n");
      out.write("<link href=\"/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"login-container\">\r\n");
      out.write("        \t<div class=\"login-logo\"><img src=\"/images/logo.png\" width=\"70\" height=\"48\" alt=\"眾騰會計師事務所\" border=\"0\"><div class=\"company-2\">測試後台</div></div>\r\n");
      out.write("        <div class=\"login-content\">\r\n");
      out.write("         <form name=\"frmAdminLogin1\" onsubmit='return isAdminLogin(1)'>\r\n");
      out.write("        \t<div class=\"id\"><input type=\"text\" name=\"adminID\" class=\"text\" placeholder=\"帳號\"></div>\r\n");
      out.write("         </form>\r\n");
      out.write("        \t<form name=\"frmAdminLogin2\" action=\"\" onsubmit='return isAdminLogin(2)' method=\"post\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"act\" value=\"process\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"adminID\">\r\n");
      out.write("        \t<div class=\"pd\"><input type=\"password\" name=\"adminPW\" class=\"text\" placeholder=\"密碼\"></div>\r\n");
      out.write("            <div class=\"ck\"><input type=\"text\" name=\"rand\" maxlength=\"4\" class=\"text3\" placeholder=\"請輸入驗證碼\" onKeyDown=\"toQuery()\"><div class=\"ckimg\"><img border=0 src=\"image.jsp\"  width=\"94\" heigh=\"34\" border=\"0\"></div></div>\r\n");
      out.write("        \t<div class=\"bt\"><input type=\"button\" value=\"送出\" class=\"login-button\" onclick='submitAdminLogin()'>\r\n");
      out.write("        \t<input type=\"reset\" value=\"取消\" class=\"login-button\"></div>\r\n");
      out.write("        \t </form>\r\n");
      out.write("         </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<script language='javascript'>\r\n");
      out.write("    function isAdminLogin (n) {\r\n");
      out.write("        var f1 = frmAdminLogin1;\r\n");
      out.write("        var f2 = frmAdminLogin2;\r\n");
      out.write("\r\n");
      out.write("        f2.adminID.value = f1.adminID.value;\r\n");
      out.write("\r\n");
      out.write("        if (n == 1) {\r\n");
      out.write("            if (f1.adminID.value == \"\") {\r\n");
      out.write("                alert (\"請輸入帳號.\");\r\n");
      out.write("                return false;\r\n");
      out.write("            } else {\r\n");
      out.write("                f2.adminPW.focus ();\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        } else if (n == 2) {\r\n");
      out.write("            if (f2.adminID.value == \"\") {\r\n");
      out.write("                alert (\"請輸入帳號.\");\r\n");
      out.write("                f1.adminID.focus ();\r\n");
      out.write("                return false;\r\n");
      out.write("            } else {\r\n");
      out.write("                if (f2.adminPW.value == \"\") {\r\n");
      out.write("                    alert (\"請輸入密碼.\");\r\n");
      out.write("                    f2.adminPW.focus ();\r\n");
      out.write("                    return false;\r\n");
      out.write("                } else {\r\n");
      out.write("                    return true;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function submitAdminLogin () {\r\n");
      out.write("        if (!isAdminLogin(2)) return;\r\n");
      out.write("        else {\r\n");
      out.write("            frmAdminLogin2.submit ();\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\tfunction toQuery(){\r\n");
      out.write("\t\tif( event.keyCode == 13 ){\r\n");
      out.write("\t\t\tsubmitAdminLogin();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
